Update the readme.
OpenSlides/openslides-media-service pull request #28
Opened 2021-10-05 12:47 UTC by reiterl

Update the readme for the media service OS4.

2021-12-02 08:22 UTC, reiterl commented
@jsangmeister  or @GabrielInTheWorld  can you pls review this, because we need to change the `Readme`.

2021-12-02 08:53 UTC, jsangmeister requested changes

2021-12-02 08:53 UTC, jsangmeister commented on README.md
> +all config must be set.
No, they all have defaults. Please provide them here

2022-07-04 06:33 UTC, jsangmeister commented
ping @reiterl

2022-07-04 07:15 UTC, reiterl commented
Rebased and added the defaults to the readme.

2022-07-04 07:17 UTC, jsangmeister approved these changes

2022-07-04 07:20 UTC, merged